#!/usr/bin/with-contenv sh

if ! [ -f "/config/args.conf" ]; then
  echo "[default-configs] restoring default 'args.conf'."
  cp /config.default/args.conf /config/
fi

if ! [ -f "/config/links.txt" ]; then
  echo "[default-configs] restoring default 'links.txt'."
  cp /config.default/links.txt /config/
fi

# always update the post-execution.sh script
echo "[default-configs] updating default 'post-execution.sh'."
cp -f /config.default/post-execution.sh /config/


ln -fs /config/args.conf /etc/yt-dlp.conf

# check if yt_dlp_quality is set, else assign default
yt_dlp_quality="${yt_dlp_quality:-best}"

# shellcheck disable=SC2016
sed -i -E 's!\$yt_dlp_quality!'"${yt_dlp_quality}"'!g' /config.default/format