#!/usr/bin/with-contenv bash

groupmod -o -g "$PGID" abc
usermod -o -u "$PUID" abc

chown -R abc:abc /app
chown -R abc:abc /config
chown -R abc:abc /downloads
chown -R abc:abc /var/run/s6/services
chown -R abc:abc /root

chmod +x /app/yt-dlp/updater.sh
chmod +x /app/yt-dlp/yt-dlp.sh
chmod +x /config/post-execution.sh
chmod +x /app/scripts/ffmpeg_encoder.sh